### ISSUE TITLE
Error thrown could be clearer when wrong content-type is given

### ISSUE THREAD

**Issue by pietercolpaert** [rubensworks/rdf-play.js#22]
When request an application/json file without JSON-LD context header, rdf-play fails with `Failed to execute 'cancel' on 'ReadableStream': Cannot cancel a locked stream`

Expected behaviour: error message `Missing context link header for media type application/json on ...`

**Comment by rubensworks** [comment]
Fixed in df3b6d1eec903dea21382b4aa1de013e43f5abba

Live version should get updated once caches are invalidated.
