### ISSUE TITLE
Not working on mobile

### ISSUE THREAD

**Issue by rubensworks** [rubensworks/rdf-play.js#4]
(At least on @RubenVerborgh's iPhone)

**Comment by rubensworks** [comment]
This may be a Safari-specific issue: https://github.com/mishoo/UglifyJS2/issues/2344

**Comment by RubenVerborgh** [comment]
Are you using Uglify still? webpack is using terser by default.

**Comment by rubensworks** [comment]
Ah, I didn't know the default changed. The error is identical, so it may also be a problem with terser then, haven't looked into it in detail yet.
